# https://github.com/Fxcilities/flask-actions/

name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
  deployment:
    - name: Test Flask Endpoints
    uses: fjogeleit/http-request-action@master
    with: # https://github.com/fjogeleit/http-request-action#input-arguments
      url: 'api endpoint1 url'
      method: 'GET'

    uses: fjogeleit/http-request-action@master
    with:
      url: 'post request endpoint url'
      method: 'POST'
      username: 'username example authorization'
      password: '1234'

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Flask
      run: |
        python -m pip install --upgrade pip
        pip install flask wsgi
    - name: Install Other Dependencies
      run: |
        pip install -r requirements.txt
    - name: Flask Tests
      run: |
        export FLASK_APP=app.py
        flask run
